# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

version: "3"

services:
   bfgd-postgres:
    build:
      dockerfile: "./e2e/postgres.Dockerfile"
      context: "./.."
    command:
      - "postgres"
      # lower random_page_cost (opposed to default 4.0) to cause planner
      # to choose index scans vs sequential scans when at fewer rows in a table
      - "-c"
      - "random_page_cost=1.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "bfg"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /data:/var
