# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

version: "3"

services:
  
  electrs:
    build:
      context: https://github.com/romanz/electrs.git#1d02f10ec38edbc3b7df6b16bb8989d9bc0aaa0f
   
    command:
      - electrs
      - --electrum-rpc-addr
      - '0.0.0.0:50001'
      - --daemon-rpc-addr
      - "localhost:8082"
      - --daemon-p2p-addr
      - "localhost:8082"
      - --network
      - testnet
      - --cookie-file
      - "/tmp/.cookie"
    volumes:
      - ./cookie:/tmp/.cookie
    deploy:
      restart_policy:
        condition: "on-failure"

  bfgd-postgres:
    build:
      dockerfile: "./e2e/postgres.Dockerfile"
      context: "./.."
    command:
      - "postgres"
      # lower random_page_cost (opposed to default 4.0) to cause planner
      # to choose index scans vs sequential scans when at fewer rows in a table
      - "-c"
      - "random_page_cost=1.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "bfg"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - { type: "tmpfs", target: "/var" }

 

volumes:
  l2configs:
